# Generated by Django 4.2.13 on 2026-07-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionTriaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nivel_urgencia', models.PositiveSmallIntegerField(choices=[(1, 'Emergencia'), (2, 'Muy urgente'), (3, 'Urgente'), (4, 'Normal'), (5, 'No urgente')], default=4, verbose_name='Nivel de urgencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (C)')),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardiaca (lpm)')),
            ],
            options={
                'verbose_name': 'Evaluacion de triaje',
                'verbose_name_plural': 'Evaluaciones de triaje',
                'ordering': ['nivel_urgencia', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('sintomas', models.TextField(verbose_name='Sintomas')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRIAJE', 'En triaje'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Solicitud de atencion',
                'verbose_name_plural': 'Solicitudes de atencion',
                'ordering': ['-creado_en'],
            },
        ),
    ]
