# Generated by Django 4.2.13 on 2026-07-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0003_mensajechat'),
        ('triaje', '0003_solicitudatencion_tipo_origen'),
    ]

    operations = [
    ]
