# Generated by Django 4.2.13 on 2026-07-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0004_merge_20260722_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudatencion',
            name='tipo_origen',
            field=models.CharField(choices=[('FORMULARIO_MANUAL', 'Formulario de síntomas'), ('CHAT_IA', 'Chat conversacional con IA'), ('ALERTA_IOT', 'Alerta por dispositivo IoT')], default='CHAT_IA', max_length=20, verbose_name='Tipo de origen'),
        ),
    ]
