# Generated by Django 4.2.13 on 2026-07-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('medicamento', models.CharField(max_length=150, verbose_name='Medicamento')),
                ('dosis', models.CharField(max_length=80, verbose_name='Dosis')),
                ('frecuencia', models.CharField(max_length=80, verbose_name='Frecuencia')),
                ('duracion', models.CharField(max_length=80, verbose_name='Duracion')),
            ],
            options={
                'verbose_name': 'Detalle de receta',
                'verbose_name_plural': 'Detalles de receta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnostico')),
            ],
            options={
                'verbose_name': 'Historial clinico',
                'verbose_name_plural': 'Historiales clinicos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('indicaciones_generales', models.TextField(blank=True, verbose_name='Indicaciones generales')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Teleconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha programada')),
                ('enlace_sala', models.URLField(blank=True, verbose_name='Enlace de sala virtual')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnostico')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de la consulta')),
            ],
            options={
                'verbose_name': 'Teleconsulta',
                'verbose_name_plural': 'Teleconsultas',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
