# Generated by Django 4.2.13 on 2026-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsulta', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='contenido_fhir',
            field=models.JSONField(blank=True, default=dict, verbose_name='Contenido FHIR'),
        ),
    ]
