# Generated by Django 4.2.13 on 2026-07-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativa'), ('ADVERTENCIA', 'Advertencia'), ('CRITICA', 'Critica')], default='INFO', max_length=20, verbose_name='Nivel')),
                ('mensaje', models.CharField(max_length=255, verbose_name='Mensaje')),
                ('atendida', models.BooleanField(default=False, verbose_name='Atendida')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('PULSERA', 'Pulsera inteligente'), ('OXIMETRO', 'Oximetro'), ('TENSIOMETRO', 'Tensiometro'), ('TERMOMETRO', 'Termometro'), ('GLUCOMETRO', 'Glucometro')], max_length=20, verbose_name='Tipo')),
                ('numero_serie', models.CharField(max_length=60, unique=True, verbose_name='Numero de serie')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LecturaBiometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('tipo_signo', models.CharField(choices=[('FRECUENCIA_CARDIACA', 'Frecuencia cardiaca (lpm)'), ('SATURACION_OXIGENO', 'Saturacion de oxigeno (%)'), ('PRESION_SISTOLICA', 'Presion sistolica (mmHg)'), ('PRESION_DIASTOLICA', 'Presion diastolica (mmHg)'), ('TEMPERATURA', 'Temperatura (C)'), ('GLUCOSA', 'Glucosa (mg/dL)')], max_length=30, verbose_name='Tipo de signo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('unidad', models.CharField(blank=True, max_length=10, verbose_name='Unidad')),
                ('fuera_de_rango', models.BooleanField(default=False, verbose_name='Fuera de rango')),
                ('tomada_en', models.DateTimeField(auto_now_add=True, verbose_name='Tomada en')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='biometria.dispositivoiot')),
            ],
            options={
                'verbose_name': 'Lectura biometrica',
                'verbose_name_plural': 'Lecturas biometricas',
                'ordering': ['-tomada_en'],
            },
        ),
    ]
