# Generated by Django 4.2.13 on 2026-07-22 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biometria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoiot',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerta',
            name='lectura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='biometria.lecturabiometrica'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lecturabiometrica',
            index=models.Index(fields=['dispositivo', 'tipo_signo'], name='biometria_l_disposi_eee392_idx'),
        ),
    ]
