# Generated by Django 4.2.13 on 2026-07-22 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoLOPDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('version_politica', models.CharField(default='1.0', max_length=10, verbose_name='Version de politica')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP')),
                ('aceptado_en', models.DateTimeField(blank=True, null=True, verbose_name='Aceptado en')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento_lopdp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento LOPDP',
                'verbose_name_plural': 'Consentimientos LOPDP',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CodigoMFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(max_length=6, verbose_name='Codigo')),
                ('expira_en', models.DateTimeField(verbose_name='Expira en')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_mfa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codigo MFA',
                'verbose_name_plural': 'Codigos MFA',
                'ordering': ['-creado_en'],
            },
        ),
    ]
