# Generated by Django 4.2.13 on 2026-07-22 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teleconsulta', '0001_initial'),
        ('triaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teleconsulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas_como_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teleconsulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas_como_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teleconsulta',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teleconsultas', to='triaje.solicitudatencion'),
        ),
        migrations.AddField(
            model_name='receta',
            name='teleconsulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='teleconsulta.teleconsulta'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='teleconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_historial', to='teleconsulta.teleconsulta'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='teleconsulta.receta'),
        ),
    ]
