# Generated by Django 4.2.13 on 2026-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsulta', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leída por el paciente'),
        ),
    ]
