# Generated by Django 4.2.13 on 2026-07-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsulta', '0003_receta_leida'),
        ('teleconsulta', '0004_idx_historial_fhir_gin'),
    ]

    operations = [
    ]
