# Generated by Django 4.2.13 on 2026-07-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('accion', models.CharField(max_length=10, verbose_name='Accion (metodo HTTP)')),
                ('ruta', models.CharField(max_length=255, verbose_name='Ruta')),
                ('codigo_estado', models.PositiveIntegerField(verbose_name='Codigo de estado HTTP')),
                ('request_id', models.CharField(blank=True, max_length=40, verbose_name='ID de peticion')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-creado_en'],
            },
        ),
    ]
