# Generated by Django 4.2.13 on 2026-07-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudatencion',
            name='tipo_origen',
            field=models.CharField(choices=[('CHAT_IA', 'Chat con IA'), ('EMERGENCIA_MANUAL', 'Emergencia solicitada manualmente'), ('ALERTA_IOT', 'Alerta generada por dispositivo IoT')], default='CHAT_IA', max_length=20, verbose_name='Tipo de origen'),
        ),
    ]
